sonar.organization=yuzhuoma816

sonar.projectKey=YuzhuoMa816_Week6_DevOps_Ex_A

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/.terraform/**,**/terraform.tfstate*,**/package-lock.json

sonar.qualitygate.wait=true